SET SERVEROUTPUT ON;

declare
    constr all_constraints.constraint_name%TYPE;
begin
    for constr in
        (select constraint_name from all_constraints
        where table_name = 'D'
        and owner = 'TRANEE')
    loop
        execute immediate 'alter table D disable constraint '||constr.constraint_name;
    end loop;
end;
/


begin 
for rec in (
           select table_name from user_tables 
           where  not   
           regexp_like(table_name, 'keep_tab1|keep_tab2|^ASB')
           
           
           ) 
loop  
    begin  
    execute immediate 'drop table '||rec.table_name || ' cascade constraints';  
    exception when others then   
    dbms_output.put_line(rec.table_name||':'||sqlerrm);  
    end;  
end loop;               
end;  
/


CREATE TABLE LOAN 
(LoanAccNumber number NOT NULL PRIMARY KEY,
Customer_ID int CONSTRAINT positive_customer_id CHECK (Customer_ID > 0),
LOANIFSC Char(11),
Principal decimal (10,2) CONSTRAINT positive_principal CHECK (Principal > 0) ,
Outstanding Decimal (10,2)  CONSTRAINT positive_outstanding CHECK (Outstanding > 0),
Loan_Type number(1) CHECK (Loan_Type > 0),
Status Varchar (20),
Approved_By_ID int,
Sanction_Date date,
Duration decimal (2,2),
CONSTRAINT check_loan_period
  CHECK (Duration between 0 and 50)
);


CREATE TABLE LOAN_TRANSACTIONS
(LOAN_TRANS_ID number generated by default as identity PRIMARY KEY,
 BRANCHIFSC CHAR (11) NOT NULL,
 LOANIFSC CHAR (11) NOT NULL,
 LoanAccNumber number NOT NULL,
 Amount Decimal (10,2) NOT NULL CONSTRAINT positive_amount CHECK (Amount > 0),
 Transaction_Date Date NOT NULL
);

CREATE TABLE LOAN_INTEREST
( INTEREST_ID number generated by default as identity PRIMARY KEY,
 LoanAccNumber number not null,
 BRANCHIFSC char (11) NOT NULL,
 Loan_Type number(1),
 Deposit_Date Date NOT NULL
 );
 


CREATE TABLE Account_Interest(
Interest_ID INT GENERATED BY DEFAULT AS IDENTITY,
Account_Number Number NOT NULL,
BranchIFSC VARCHAR(11) NOT NULL,
Created_Date DATE NOT NULL,
PRIMARY KEY (Interest_ID)
);

CREATE TABLE Account_Status(
Status_ID INT GENERATED BY DEFAULT AS IDENTITY,
Account_Number NUMBER NOT NULL,
Status VARCHAR(20) NOT NULL,
Created_Date DATE NOT NULL,
PRIMARY KEY (Status_ID)
);

CREATE TABLE WORKS_WITH(
Customer_ID INT NOT NULL,
Employee_ID INT NOT NULL,
Relationship varchar(20),
PRIMARY KEY (Customer_ID,Employee_ID)
);

CREATE TABLE Branch_Supplier (
Supplier_ID int PRIMARY KEY,
Supplier_Name  VARCHAR(20) NOT NULL,
Supplier_Type  VARCHAR(20),
Branch_ID NUMBER
);



CREATE TABLE EMPLOYEE 
   (
    EMPLOYEE_ID NUMBER NOT NULL, 
	BRANCH_ID NUMBER(10,0) NOT NULL, 
	DEPARTMENT VARCHAR2(20 BYTE) NOT NULL, 
	FIRST_NAME VARCHAR2(20 BYTE) NOT NULL, 
	LAST_NAME VARCHAR2(20 BYTE), 
	SEX CHAR(1), 
	DOB DATE, 
	SALARY NUMBER(10,2), 
	EMP_ROLE VARCHAR2(20 BYTE), 
	EMAIL_ID VARCHAR2(40 BYTE) UNIQUE, 
	CONTACT_NO NUMBER(10,0) NOT NULL UNIQUE, 
	SUPERVISOR_ID NUMBER, 
	 CONSTRAINT "EMP_EMPLOYEE_ID" CHECK ( Employee_Id > 0 ), 
	 CONSTRAINT "EMP_BRANCH_ID" CHECK (Branch_Id > 0 ), 
	 CONSTRAINT "GENDER_CHECK" CHECK (Sex IN ('F','M','O')), 
	 CONSTRAINT "SAL_CHECK" CHECK (Salary > 0 ), 
	 CONSTRAINT "CONTACT_CHECK" CHECK ( LENGTH(CONTACT_NO) = 10 ), 
	 PRIMARY KEY ("EMPLOYEE_ID")
    ); 
    

CREATE TABLE TRANSACTIONS(

    Tansaction_ID   int primary key,
    Debit_Account   number,
    Credit_Account  number,
    IFSC_Code_Debit char(11),
    IFSC_Code_Credit char (11),
    Amount          Decimal(10,2) not null constraint amt_check check( Amount > 0),
    Transaction_date date,
    Message         varchar(100),
    Status          varchar(20)

);



CREATE TABLE CUSTOMER(
Customer_ID INT PRIMARY KEY,
First_Name VARCHAR(20) NOT NULL,
Last_Name VARCHAR(20) NOT NULL,
DOB Date,
Works_at VARCHAR(20),
Sex VARCHAR(1) CONSTRAINT Genders CHECK(Sex IN ('M','F','O')),
Apt_No VARCHAR(20),
Street VARCHAR(20),
City VARCHAR(20),
CState VARCHAR(2),
Zipcode int CONSTRAINT Zip_Length CHECK (LENGTH(Zipcode)=5),
Phone int UNIQUE CONSTRAINT Phone_Length CHECK(LENGTH(Phone)=10)
);


CREATE TABLE Account(
AccountNumber NUMBER NOT NULL,
Account_Type VARCHAR(20) NOT NULL,
BranchIFSC CHAR(11) NOT NULL,
Customer_ID INT,
Account_Balance DECIMAL NOT NULL CONSTRAINT Balance_Positive CHECK (Account_Balance > 0),
PRIMARY KEY (AccountNumber)
);

 CREATE TABLE LOAN_TYPE
( Loan_Type number(1) PRIMARY KEY CHECK (Loan_Type > 0),
Interest_Rate decimal (2,2) CONSTRAINT positive_interest_rate CHECK (Interest_Rate > 0),
Category varchar (20) NOT NULL
);

CREATE TABLE Branch (
BranchIFSC Char(11) PRIMARY KEY CONSTRAINT elevenchar CHECK (length(BranchIFSC)=11),
Branch_ID   int UNIQUE,
Address  VARCHAR(20) NOT NULL,
Street  VARCHAR(20)NOT NULL,
City   VARCHAR(20) NOT NULL,
State Char(2) NOT NULL,
Zipcode int,
Manager_ID int CONSTRAINT Positive_Manager_ID CHECK(Manager_ID>0)
);

-- Branch (NO FK)


-- Branch Supplier
ALTER TABLE Branch_Supplier ADD CONSTRAINT FK_Branch_ID FOREIGN KEY (Branch_ID) REFERENCES Branch(Branch_ID) ON DELETE CASCADE;

-- Transactions
ALTER TABLE Transactions ADD CONSTRAINT FK_Debit_Account FOREIGN KEY (Debit_Account) REFERENCES Account(AccountNumber)ON DELETE CASCADE;
ALTER TABLE Transactions ADD CONSTRAINT FK_Credit_Account FOREIGN KEY (Credit_Account) REFERENCES Account(AccountNumber)ON DELETE CASCADE;

-- Account Status
ALTER TABLE Account_Status ADD CONSTRAINT FK_Acc_Number FOREIGN KEY (Account_Number) REFERENCES Account(AccountNumber)ON DELETE CASCADE;

-- Account Interest
ALTER TABLE Account_Interest ADD CONSTRAINT FK_AccInterest_Acc_Number FOREIGN KEY (Account_Number) REFERENCES Account(AccountNumber)ON DELETE CASCADE;

-- Account
ALTER TABLE Account ADD CONSTRAINT FK_Account_Customer_ID FOREIGN KEY (Customer_ID) REFERENCES Customer(Customer_ID) ON DELETE CASCADE;

-- Loan
ALTER TABLE Loan ADD CONSTRAINT FK_Customer_ID FOREIGN KEY (Customer_ID) REFERENCES Customer(Customer_ID)ON DELETE CASCADE;
ALTER TABLE Loan ADD CONSTRAINT FK_Loan_Type FOREIGN KEY (Loan_Type) REFERENCES Loan_Type(Loan_Type)ON DELETE CASCADE;
ALTER TABLE Loan ADD CONSTRAINT FK_Loan_IFSC FOREIGN KEY (LOANIFSC) REFERENCES Branch(BranchIFSC)ON DELETE CASCADE;
ALTER TABLE Loan ADD CONSTRAINT FK_Sanction_ID FOREIGN KEY (Approved_By_ID) REFERENCES Employee(Employee_ID)ON DELETE CASCADE;

-- Loan Transactions

ALTER TABLE Loan_Transactions ADD CONSTRAINT FK_LIFSC FOREIGN KEY (LoanIFSC) REFERENCES Branch(BranchIFSC)ON DELETE CASCADE;
ALTER TABLE Loan_Transactions ADD CONSTRAINT FK_LoanAccNumber FOREIGN KEY (LoanAccNumber) REFERENCES Loan(LoanAccNumber)ON DELETE CASCADE;

-- Loan Interest
ALTER TABLE Loan_Interest ADD CONSTRAINT FK_Interest_LoanAccNumber FOREIGN KEY (LoanAccNumber) REFERENCES Loan(LoanAccNumber)ON DELETE CASCADE;
ALTER TABLE Loan_Interest ADD CONSTRAINT FK_Loan_Interest_IFSC FOREIGN KEY (BranchIFSC) REFERENCES Branch(BranchIFSC)ON DELETE CASCADE;
ALTER TABLE Loan_Interest ADD CONSTRAINT FK_Loan_Interst_Loan_Type FOREIGN KEY (Loan_Type) REFERENCES Loan_Type(Loan_Type) ON DELETE CASCADE;
--
-- Loan_Type (NO FK) 

-- Works With
ALTER TABLE Works_With ADD CONSTRAINT FK_Works_With_Emp FOREIGN KEY (Employee_ID) REFERENCES Employee(Employee_ID) ON DELETE CASCADE;
ALTER TABLE Works_With ADD CONSTRAINT FK_Works_With_Customer FOREIGN KEY (Customer_ID) REFERENCES Customer(Customer_ID) ON DELETE CASCADE;

-- Employee
ALTER TABLE Employee ADD CONSTRAINT FK_Emp_Branch FOREIGN KEY (Branch_ID) REFERENCES Branch(Branch_ID) ON DELETE CASCADE;

-- Customer (NO FK)


-- Data Inserting Branch
INSERT INTO BRANCH VALUES ('DMDD0454500',1,'405 Huntington Ave','Park Street','Boston','MA',02120,012324);
INSERT INTO BRANCH VALUES ('DMDD0101022',2,'111 Howard Ave','Tremont Street','Boston','MA',02180,055564);
INSERT INTO BRANCH VALUES ('DMDD0333100',3,'333 Longwood Ave','Milk Street','Boston','MA',02190,037567);

-- Data Inserting Employee
INSERT INTO EMPLOYEE VALUES (012324, 1, 'Research', 'Akarsh', 'Singh', 'M',TO_DATE('1999-03-09','YYYY-MM-DD'), 120000, 'Branch Manager', 'akarshsinghh@gmail.com', 7710037766, '');
INSERT INTO EMPLOYEE VALUES (055564, 2, 'Sales', 'Alex', 'ONeil', 'M',TO_DATE('1997-10-06','YYYY-MM-DD'), 115000, 'Branch Manager', 'neilalex32@gmail.com', 8910037766, '');
INSERT INTO EMPLOYEE VALUES (037567, 3, 'Sales', 'Kylie', 'James', 'F',TO_DATE('1992-11-01','YYYY-MM-DD'), 130000, 'Branch Manager', 'thekyliejames@outlook.com', 8910032459, '');
INSERT INTO EMPLOYEE VALUES (036940, 3, 'Sales', 'Megan', 'Smith', 'F',TO_DATE('1999-06-30','YYYY-MM-DD'), 67000, 'Accountant', 'megans30@outlook.com', 8910076403, 037567);
INSERT INTO EMPLOYEE VALUES (036113, 3, 'Software', 'Ravi', 'Teja', 'M',TO_DATE('1998-06-13','YYYY-MM-DD'), 90000, 'Developer', 'tejaravi_tv@gmail.com', 8570076403, '');
INSERT INTO EMPLOYEE VALUES (036999, 3, 'Sales', 'Charlottee', 'Malik', 'F',TO_DATE('1997-02-12','YYYY-MM-DD'), 75000, 'Relationship Officer', 'mcharlottee@outlook.com', 8579076403, 037567);
INSERT INTO EMPLOYEE VALUES (036941, 3, 'Marketing', 'Chang', 'Cho', 'O',TO_DATE('1995-03-24','YYYY-MM-DD'), 77000, 'Head', 'chochangg@outlook.com', 8910076507, '');
INSERT INTO EMPLOYEE VALUES (036942, 3, 'Operations', 'John', 'Ledger', 'M',TO_DATE('1998-06-17','YYYY-MM-DD'), 85000, 'Associate', 'johnl@yahoo.com', 8910071122, 011818);
INSERT INTO EMPLOYEE VALUES (036933, 3, 'Operations', 'Mark', 'Benetton', 'M',TO_DATE('1997-10-30','YYYY-MM-DD'), 84000, 'Associate', 'markbene@outlook.com', 8910072241, 011818);
INSERT INTO EMPLOYEE VALUES (011818, 3, 'Operations', 'Grace', 'Fernandes', 'F',TO_DATE('1982-09-27','YYYY-MM-DD'), 93000, 'Senior Associate', 'gracefernandes30@gmail.com', 8910078979, 037567);
INSERT INTO EMPLOYEE VALUES (056940, 2, 'Sales', 'Josh', 'Jacobs', 'M',TO_DATE('1987-07-18','YYYY-MM-DD'), 69000, 'Accountant', 'srjjacobs@outlook.com', 7120076403,055564);
INSERT INTO EMPLOYEE VALUES (056941, 2, 'Sales', 'Megan', 'Smith', 'F',TO_DATE('1999-06-30','YYYY-MM-DD'), 67000, 'Accountant', 'megansmithh@yahoo.com', 7770076403,055564);
INSERT INTO EMPLOYEE VALUES (056942, 2, 'Operations', 'Elle', 'Bridge', 'F',TO_DATE('1996-08-29','YYYY-MM-DD'), 72000, 'Associate', 'bridgeelle101@outlook.com', 8880072403, 059999);
INSERT INTO EMPLOYEE VALUES (056943, 2, 'Operations', 'Blake', 'Springer', 'M',TO_DATE('1994-06-30','YYYY-MM-DD'), 87000, 'Associate', 'springer.blake@gmail.com', 8999076403, 059999);
INSERT INTO EMPLOYEE VALUES (059999, 2, 'Operations', 'Ajit', 'Poonawala','O',TO_DATE('1975-10-21','YYYY-MM-DD'), 105000, 'Lead Associate', 'poonawal.ajit1@gmail.com', 8999076400, 055564);
INSERT INTO EMPLOYEE VALUES (016940, 1, 'Sales', 'Ram', 'Charan', 'M',TO_DATE('1986-04-18','YYYY-MM-DD'), 69000, 'Accountant', 'rcharan@outlook.com', 8120076403,012324);
INSERT INTO EMPLOYEE VALUES (016941, 1, 'Sales', 'Sharvi', 'Jaffery', 'F',TO_DATE('1999-04-17','YYYY-MM-DD'), 67000, 'Accountant', 'sharvijj@gmail.com', 8770076403,012324);
INSERT INTO EMPLOYEE VALUES (016942, 1, 'Operations', 'Darren', 'Franco', 'M',TO_DATE('1993-08-29','YYYY-MM-DD'), 77000, 'Associate', 'd.franco@outlook.com', 8780076403, 019999);
INSERT INTO EMPLOYEE VALUES (016943, 1, 'Operations', 'Cherry', 'Chan', 'O',TO_DATE('1997-01-05','YYYY-MM-DD'), 72000, 'Associate', 'chancherry05@gmail.com', 7699076403, 019999);
INSERT INTO EMPLOYEE VALUES (019999, 1, 'Operations', 'Nick', 'Bilzerian','M',TO_DATE('1971-11-22','YYYY-MM-DD'), 107000, 'Lead Associate', 'bilznick71@gmail.com', 8000076403, 012324);

-- Customer

INSERT INTO Customer values('100000','John','Sander','12-05-1988','NE','M','14','Calumet St', 'Boston', 'MA', '12345', '9999999999');
INSERT INTO Customer values('100001','Adam','Levine','11-04-1990','NE','M','14','Milk Street', 'Boston', 'MA', '12345', '9658365933');
INSERT INTO Customer values('100002','Josh', 'Curry','11-04-1990','NE','M','15','Park Street', 'Boston', 'MA', '12345', '8572212077');
INSERT INTO Customer values('100003','Lakshana','Kolur','07-11-1985','SE','F','05','South End Street', 'Boston', 'MA', '12345', '7575838485');
INSERT INTO Customer values('100004','Clara','Goerge','21-07-1981','SE','F','03','Hill Road', 'Boston', 'MA', '12345', '7863542435');
INSERT INTO Customer values('100005','Meghan','Ritter','01-11-1972','NE','F','14','Carter Street', 'Boston', 'MA', '12345', '8755235554');
INSERT INTO Customer values('100006','Rajdeep','Mamtani','12-03-1979','SE','M','14','Mac Street', 'Allston', 'MA', '12345', '7843563450');
INSERT INTO Customer values('100007','Sonal','Singh','18-01-1988','SE','F','23','Shipman Street', 'Allston', 'MA', '12345', '8954398443');
INSERT INTO Customer values('100008','Jayashree','Kumari','14-06-1984','SE','F','14','India Street', 'Allston', 'MA', '12345', '9787837854');
INSERT INTO Customer values('100009','Harper','Selter','06-06-1966','SE','F','11','Mass Ave', 'Cambridge', 'MA', '12345', '9827354354');
INSERT INTO Customer values('100010','Amol', 'Srivatsav','09-05-1987','SE','O','08','Dennis Ave', 'Cambridge', 'MA', '12345', '9873455445');
INSERT INTO Customer values('100011','Abhimanyu','Sarda','12-05-1990','NE','O','14','Huntington Ave', 'Cambridge', 'MA', '12345', '8754493433');
INSERT INTO Customer values('100012','Amy', 'Hazarika','11-05-1987','NE','F','14','7th Ave', 'Cambridge', 'MA', '12345', '9865489380');
INSERT INTO Customer values('100013', 'Tracy' ,'Zelensky','12-05-1988','SE','F','14','Light Road', 'Boston', 'MA', '12345', '7893548993');
INSERT INTO Customer values('100014','Sharron', 'Naim','12-05-1988','SE','F','14','Sea Street', 'Boston', 'MA', '12345', '8889876543');
INSERT INTO Customer values('100015','Charlie', 'Watson','12-05-1988','NE','F','14','13th Street', 'Amherst', 'MA', '12345', '7878676887');
INSERT INTO Customer values('100016','Mrinal', 'Kumar','08-08-1991','NE','M','14','Curry Road', 'Amherst', 'MA', '12345', '7665687670');
INSERT INTO Customer values('100017','Margot', 'Pincha','12-05-1988','SE','F','21','Belmont St', 'Amherst', 'MA', '12345', '8765432109');
INSERT INTO Customer values('100018','Sowmya', 'Raghavan','12-05-1988','NE','M','14','Oak Road', 'Amherst', 'MA', '12345', '8765409876');
INSERT INTO Customer values('100019','Anukriti','Joshi','19-09-1981','NE','M','14','Darling St', 'Cambridge', 'MA', '12345', '8754290454');

















