Drop table transactions;

CREATE TABLE transactions (
    tansaction_id    INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1999999999999 INCREMENT BY 1) PRIMARY KEY,
    debit_account    NUMBER,
    credit_account   NUMBER,
    ifsc_code_debit  CHAR(11),
    ifsc_code_credit CHAR(11),
    amount           DECIMAL(10, 2) NOT NULL
        CONSTRAINT amt_check CHECK ( amount > 0 ),
    transaction_date DATE,
    message          VARCHAR(100),
    status           VARCHAR(20)
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    13719713158835300,
    1086643758945400,
    'DMDD0454500',
    'DMDD0101022',
    '20.00',
    DATE '2021-03-08',
    'sent $20',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    53153834006064000,
    3719713158855555,
    'DMDD0101022',
    'DMDD0454500',
    '40.00',
    DATE '2021-04-11',
    'Amount $40 Transferred',
    'Success'
);

INSERT INTO transactions (

    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (

    37530666568966100,
    70048841700216300,
    'DMDD0333100',
    'DMDD0454500',
    '250.00',
    DATE '2022-10-10',
    'sent $250',
    'Pending'
);

INSERT INTO transactions (

    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (

    89135767380499400,
    12494980148173100,
    'DMDD0101022',
    'DMDD0333100',
    '50.00',
    DATE '2021-11-08',
    'sent $50',
    'Success'
);

INSERT INTO transactions (

    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (

    8744336085399580,
    64289489845768000,
    'DMDD0101022',
    'DMDD0454500',
    '330.00',
    DATE '2022-04-08',
    'sent $330',
    'Success'
);

INSERT INTO transactions (

    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (

    70149340835549500,
    13719713158835300,
    'DMDD0333100',
    'DMDD0454500',
    '150.00',
    DATE '2020-05-18',
    'sent $150',
    'Success'
);

INSERT INTO transactions (

    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    9560713158835400,
    9009713158835400,
    'DMDD0454500',
    'DMDD0101022',
    '120.00',
    DATE '2021-02-23',
    'sent $120',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    53153834006064000,
    3690859741294280,
    'DMDD0101022',
    'DMDD0454500',
    '400.00',
    DATE '2020-08-05',
    'Amount $400 Transferred',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    37530666568966100,
    70048841700216300,
    'DMDD0333100',
    'DMDD0454500',
    '500.00',
    DATE '2022-01-18',
    'sent $500',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    89135767380499400,
    12494980148173100,
    'DMDD0101022',
    'DMDD0333100',
    '350.00',
    DATE '2021-07-28',
    'sent $350',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    8744336085399580,
    64289489845768000,
    'DMDD0101022',
    'DMDD0454500',
    '444.00',
    DATE '2021-10-04',
    'sent $444',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (

    70149340835549500,
    13719713158835300,
    'DMDD0333100',
    'DMDD0454500',
    '100.00',
    DATE '2021-02-11',
    'sent $100',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    13719713158835300,
    1086643758945400,
    'DMDD0454500',
    'DMDD0101022',
    '1000.00',
    DATE '2021-03-08',
    'sent $1000',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (

    53153834006064000,
    3690859741294280,
    'DMDD0101022',
    'DMDD0454500',
    '700.00',
    DATE '2021-08-29',
    'Amount $700 Transferred',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    37530666568966100,
    70048841700216300,
    'DMDD0333100',
    'DMDD0454500',
    '750.00',
    DATE '2021-10-10',
    'sent $750',
    'Pending'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    89135767380499400,
    12494980148173100,
    'DMDD0101022',
    'DMDD0333100',
    '55.00',
    DATE '2021-11-09',
    'sent $55',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    8744336085399580,
    64289489845768000,
    'DMDD0101022',
    'DMDD0454500',
    '360.00',
    DATE '2021-10-03',
    'sent $360',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    70149340835549500,
    13719713158835300,
    'DMDD0333100',
    'DMDD0454500',
    '66.00',
    DATE '2020-09-03',
    'sent $66',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    13719713158835300,
    1086643758945400,
    'DMDD0454500',
    'DMDD0101022',
    '450.00',
    DATE '2021-08-01',
    'sent $450',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    53153834006064000,
    3690859741294280,
    'DMDD0101022',
    'DMDD0454500',
    '600.00',
    DATE '2021-01-01',
    'Amount $600 Transferred',
    'Success'
);

INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    37530666568966100,
    70048841700216300,
    'DMDD0333100',
    'DMDD0454500',
    '60.00',
    DATE '2022-04-13',
    'sent $60',
    'Success'
);

INSERT INTO transactions (
    credit_account,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    3690859741294280,
    'DMDD0454500',
    '1000.00',
    DATE '2020-03-08',
    'Deposit of $1000',
    'Success'
);

INSERT INTO transactions (
    credit_account,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    37530666568966100,
    'DMDD0333100',
    '2000.00',
    DATE '2020-04-07',
    'Deposit of $2000',
    'Success'
);

INSERT INTO transactions (
    credit_account,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    70048841700216300,
    'DMDD0454500',
    '2000.00',
    DATE '2019-05-06',
    'Deposit of $2000',
    'Success'
);

INSERT INTO transactions (
    credit_account,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    89135767380499400,
    'DMDD0101022',
    '2000.00',
    DATE '2021-06-05',
    'Deposit of $2000',
    'Success'
);

INSERT INTO transactions (
    credit_account,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    12494980148173100,
    'DMDD0333100',
    '2300.00',
    DATE '2018-07-04',
    'Deposit of $2300',
    'Success'
);

INSERT INTO transactions (
    credit_account,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    8744336085399580,
    'DMDD0101022',
    '2000.00',
    DATE '2021-08-03',
    'Deposit of $2000',
    'Success'
);

INSERT INTO transactions (
    credit_account,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    64289489845768000,
    'DMDD0454500',
    '2100.00',
    DATE '2021-09-02',
    'Deposit of $2100',
    'Success'
);

INSERT INTO transactions (
    credit_account,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    70149340835549500,
    'DMDD0333100',
    '2200.00',
    DATE '2019-10-21',
    'Deposit of $2200',
    'Success'
);

INSERT INTO transactions (
    credit_account,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    71086643758945400,
    'DMDD0101022',
    '2200.00',
    DATE '2020-02-09',
    'Deposit of $2200',
    'Success'
);


INSERT INTO transactions (
    debit_account,
    credit_account,
    ifsc_code_debit,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    71086643758945400,
    70149340835549500,
    'DMDD0101022',
    'DMDD0333100',
    '350.00',
    DATE '2020-03-10',
    'sent $350',
    'Success'
);

INSERT INTO transactions (
    credit_account,
    ifsc_code_credit,
    amount,
    transaction_date,
    message,
    status
) VALUES (
    13719713158835300,
    'DMDD0454500',
    '2000.00',
    DATE '2019-01-05',
    'Deposit of $2000',
    'Success'
);

SELECT *
FROM transactions order by transaction_date;